### PR TITLE
Template CDN jQuery with Ajax

### PR DESCRIPTION
**Pull request by alejandrogarciapalomo**
Include CDN  jQuery with Ajax support

### CODE REVIEW

**Comment by Eventyret** [comment]
Thanks for doing this @alejandrogarciapalomo .
I will instead of merge this in a change to make it default, Ajax should be supported out of the box and it's no point of making a new snippet just for ajax support, what do you think ?

**Comment by alejandrogarciapalomo** [comment]
In the official version of Bootstrap they normally use the Slim version of jQuery (https://getbootstrap.com/docs/4.3/getting-started/introduction/) but sometimes you need ajax. I think that you can find both snippets. If you want to use only one, I would use the version without slim of jQuery

**Comment by Eventyret** [comment]
I will update a new version and close this issue @alejandrogarciapalomo or you can create a new PR with just the change from SLIM if you want to that way we get ajax and we don't give it to much of customization. Feel free to close this and create a new PR changing slim to normal

**Comment by alejandrogarciapalomo** [comment]
Two versions like my code it´s ok. You can update! Thanks!!

**Review by Eventyret — APPROVED** [review]

**Comment by Eventyret** [comment]
Thanks @alejandrogarciapalomo I have published 1.1.8 for this. Again thanks for the PR

**Pull request merged**
